In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":["ashu","atharva","amit","vijay"],
    "marks":[78,97,85,82],
    "city":['pune','mumbai','delhi','banglore']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

      name  marks      city
0     ashu     78      pune
1  atharva     97    mumbai
2     amit     85     delhi
3    vijay     82  banglore

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_index_false.csv', index=False)

In [7]:
df.head(2)

      name  marks    city
0     ashu     78    pune
1  atharva     97  mumbai

In [8]:
df.tail(2)

    name  marks      city
2   amit     85     delhi
3  vijay     82  banglore

In [9]:
df.describe()

           marks
count   4.000000
mean   85.500000
std     8.185353
min    78.000000
25%    81.000000
50%    83.500000
75%    88.000000
max    97.000000

In [10]:
ashu = pd.read_csv('ashu.csv')

In [11]:
ashu

   Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Train No  Speed      City
0             0             0           0       123    100      pune
1             1             1           1       456    222    mumbai
2             2             2           2       789    333     delhi
3             3             3           3       901    212  banglore

In [12]:
ashu['Speed']

0    100
1    222
2    333
3    212
Name: Speed, dtype: int64

In [13]:
ashu['Speed'][0]

np.int64(100)

In [14]:
ashu['Speed'][0] = 100

C:\Users\HP\AppData\Local\Temp\ipykernel_8104\3091258740.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ashu['Speed'][0] = 100

In [15]:
ashu.to_csv('ashu.csv')

In [16]:
ashu

   Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Train No  Speed      City
0             0             0           0       123    100      pune
1             1             1           1       456    222    mumbai
2             2             2           2       789    333     delhi
3             3             3           3       901    212  banglore

In [17]:
ashu.index = ['first','second','third','fourth']

In [18]:
ashu

        Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Train No  Speed      City
first              0             0           0       123    100      pune
second             1             1           1       456    222    mumbai
third              2             2           2       789    333     delhi
fourth             3             3           3       901    212  banglore

In [19]:
ser = pd.Series(np.random.rand)

In [20]:
ser

0    <bound method RandomState.rand of RandomState(...
dtype: object

In [21]:
ser = pd.Series(np.random.rand(34))

In [22]:
ser

0     0.881341
1     0.170683
2     0.345333
3     0.992257
4     0.377082
5     0.120823
6     0.313584
7     0.189531
8     0.091228
9     0.375829
10    0.245042
11    0.178750
12    0.006661
13    0.169132
14    0.572633
15    0.881578
16    0.564235
17    0.317225
18    0.721166
19    0.443313
20    0.838390
21    0.488139
22    0.397947
23    0.602020
24    0.767848
25    0.309860
26    0.506751
27    0.053932
28    0.078014
29    0.806910
30    0.606612
31    0.747461
32    0.084792
33    0.814753
dtype: float64

In [23]:
type(ser)

pandas.core.series.Series

In [24]:
newdf = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [25]:
newdf.head()

          0         1         2         3         4
0  0.035018  0.776558  0.769921  0.621858  0.038960
1  0.950114  0.889519  0.817604  0.582885  0.646131
2  0.979222  0.231910  0.205309  0.225336  0.717991
3  0.471485  0.774292  0.205895  0.623574  0.648689
4  0.013309  0.919097  0.670957  0.913508  0.307098

In [26]:
newdf

            0         1         2         3         4
0    0.035018  0.776558  0.769921  0.621858  0.038960
1    0.950114  0.889519  0.817604  0.582885  0.646131
2    0.979222  0.231910  0.205309  0.225336  0.717991
3    0.471485  0.774292  0.205895  0.623574  0.648689
4    0.013309  0.919097  0.670957  0.913508  0.307098
..        ...       ...       ...       ...       ...
329  0.440569  0.341099  0.164204  0.542524  0.973557
330  0.627435  0.237973  0.083605  0.982653  0.993708
331  0.605874  0.653563  0.578146  0.546774  0.974497
332  0.952195  0.089713  0.325029  0.684682  0.597397
333  0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [27]:
type(newdf)

pandas.core.frame.DataFrame

In [28]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.502401    0.492506    0.482720    0.489969    0.491931
std      0.294293    0.289383    0.287257    0.283027    0.291156
min      0.002772    0.001200    0.000774    0.000571    0.005264
25%      0.240028    0.237310    0.231580    0.255400    0.247295
50%      0.514679    0.468215    0.443940    0.487436    0.473743
75%      0.764752    0.744184    0.740428    0.743229    0.750706
max      0.999601    0.996464    0.997908    0.993891    0.998621

In [29]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [30]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [31]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [32]:
newdf.to_numpy()

array([[0.03501762, 0.77655751, 0.76992086, 0.62185841, 0.03895992],
       [0.95011375, 0.88951881, 0.81760427, 0.5828851 , 0.64613056],
       [0.97922243, 0.23191022, 0.20530922, 0.22533625, 0.717991  ],
       ...,
       [0.60587449, 0.65356319, 0.57814629, 0.546774  , 0.97449674],
       [0.95219502, 0.08971337, 0.32502875, 0.68468214, 0.59739734],
       [0.55936088, 0.66204261, 0.07797253, 0.98724575, 0.27084578]],
      shape=(334, 5))

In [33]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.035018,0.950114,0.979222,0.471485,0.013309,0.819628,0.195840,0.702920,0.462522,0.483673,...,0.405878,0.301542,0.110436,0.179691,0.915727,0.440569,0.627435,0.605874,0.952195,0.559361
1,0.776558,0.889519,0.231910,0.774292,0.919097,0.652225,0.759065,0.015971,0.552297,0.421993,...,0.420782,0.103719,0.650766,0.952231,0.436628,0.341099,0.237973,0.653563,0.089713,0.662043
2,0.769921,0.817604,0.205309,0.205895,0.670957,0.829547,0.207983,0.303954,0.056003,0.307215,...,0.798278,0.386660,0.327397,0.120670,0.524658,0.164204,0.083605,0.578146,0.325029,0.077973
3,0.621858,0.582885,0.225336,0.623574,0.913508,0.668876,0.283971,0.231726,0.298986,0.168338,...,0.463282,0.987452,0.390520,0.225822,0.283107,0.542524,0.982653,0.546774,0.684682,0.987246
4,0.038960,0.646131,0.717991,0.648689,0.307098,0.248237,0.801792,0.697766,0.688767,0.156068,...,0.077221,0.874008,0.830910,0.253380,0.611358,0.973557,0.993708,0.974497,0.597397,0.270846

In [34]:
newdf

            0         1         2         3         4
0    0.035018  0.776558  0.769921  0.621858  0.038960
1    0.950114  0.889519  0.817604  0.582885  0.646131
2    0.979222  0.231910  0.205309  0.225336  0.717991
3    0.471485  0.774292  0.205895  0.623574  0.648689
4    0.013309  0.919097  0.670957  0.913508  0.307098
..        ...       ...       ...       ...       ...
329  0.440569  0.341099  0.164204  0.542524  0.973557
330  0.627435  0.237973  0.083605  0.982653  0.993708
331  0.605874  0.653563  0.578146  0.546774  0.974497
332  0.952195  0.089713  0.325029  0.684682  0.597397
333  0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [35]:
newdf.head()

          0         1         2         3         4
0  0.035018  0.776558  0.769921  0.621858  0.038960
1  0.950114  0.889519  0.817604  0.582885  0.646131
2  0.979222  0.231910  0.205309  0.225336  0.717991
3  0.471485  0.774292  0.205895  0.623574  0.648689
4  0.013309  0.919097  0.670957  0.913508  0.307098

In [36]:
newdf.sort_index(axis=0, ascending= False)

            0         1         2         3         4
333  0.559361  0.662043  0.077973  0.987246  0.270846
332  0.952195  0.089713  0.325029  0.684682  0.597397
331  0.605874  0.653563  0.578146  0.546774  0.974497
330  0.627435  0.237973  0.083605  0.982653  0.993708
329  0.440569  0.341099  0.164204  0.542524  0.973557
..        ...       ...       ...       ...       ...
4    0.013309  0.919097  0.670957  0.913508  0.307098
3    0.471485  0.774292  0.205895  0.623574  0.648689
2    0.979222  0.231910  0.205309  0.225336  0.717991
1    0.950114  0.889519  0.817604  0.582885  0.646131
0    0.035018  0.776558  0.769921  0.621858  0.038960

[334 rows x 5 columns]

In [37]:
newdf.sort_index(axis=0, ascending=False)
newdf.head()

          0         1         2         3         4
0  0.035018  0.776558  0.769921  0.621858  0.038960
1  0.950114  0.889519  0.817604  0.582885  0.646131
2  0.979222  0.231910  0.205309  0.225336  0.717991
3  0.471485  0.774292  0.205895  0.623574  0.648689
4  0.013309  0.919097  0.670957  0.913508  0.307098

In [38]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.559361  0.662043  0.077973  0.987246  0.270846
332  0.952195  0.089713  0.325029  0.684682  0.597397
331  0.605874  0.653563  0.578146  0.546774  0.974497
330  0.627435  0.237973  0.083605  0.982653  0.993708
329  0.440569  0.341099  0.164204  0.542524  0.973557
..        ...       ...       ...       ...       ...
4    0.013309  0.919097  0.670957  0.913508  0.307098
3    0.471485  0.774292  0.205895  0.623574  0.648689
2    0.979222  0.231910  0.205309  0.225336  0.717991
1    0.950114  0.889519  0.817604  0.582885  0.646131
0    0.035018  0.776558  0.769921  0.621858  0.038960

[334 rows x 5 columns]

In [39]:
newdf.sort_index(axis=1, ascending=False)

            4         3         2         1         0
0    0.038960  0.621858  0.769921  0.776558  0.035018
1    0.646131  0.582885  0.817604  0.889519  0.950114
2    0.717991  0.225336  0.205309  0.231910  0.979222
3    0.648689  0.623574  0.205895  0.774292  0.471485
4    0.307098  0.913508  0.670957  0.919097  0.013309
..        ...       ...       ...       ...       ...
329  0.973557  0.542524  0.164204  0.341099  0.440569
330  0.993708  0.982653  0.083605  0.237973  0.627435
331  0.974497  0.546774  0.578146  0.653563  0.605874
332  0.597397  0.684682  0.325029  0.089713  0.952195
333  0.270846  0.987246  0.077973  0.662043  0.559361

[334 rows x 5 columns]

In [40]:
newdf.head()

          0         1         2         3         4
0  0.035018  0.776558  0.769921  0.621858  0.038960
1  0.950114  0.889519  0.817604  0.582885  0.646131
2  0.979222  0.231910  0.205309  0.225336  0.717991
3  0.471485  0.774292  0.205895  0.623574  0.648689
4  0.013309  0.919097  0.670957  0.913508  0.307098

In [41]:
newdf[0]

0      0.035018
1      0.950114
2      0.979222
3      0.471485
4      0.013309
         ...
329    0.440569
330    0.627435
331    0.605874
332    0.952195
333    0.559361
Name: 0, Length: 334, dtype: float64

In [42]:
type(newdf[0])

pandas.core.series.Series

In [44]:
newdf.head()

          0         1         2         3         4
0  0.035018  0.776558  0.769921  0.621858  0.038960
1  0.950114  0.889519  0.817604  0.582885  0.646131
2  0.979222  0.231910  0.205309  0.225336  0.717991
3  0.471485  0.774292  0.205895  0.623574  0.648689
4  0.013309  0.919097  0.670957  0.913508  0.307098

In [45]:
newdf2 = newdf

In [46]:
newdf2

            0         1         2         3         4
0    0.035018  0.776558  0.769921  0.621858  0.038960
1    0.950114  0.889519  0.817604  0.582885  0.646131
2    0.979222  0.231910  0.205309  0.225336  0.717991
3    0.471485  0.774292  0.205895  0.623574  0.648689
4    0.013309  0.919097  0.670957  0.913508  0.307098
..        ...       ...       ...       ...       ...
329  0.440569  0.341099  0.164204  0.542524  0.973557
330  0.627435  0.237973  0.083605  0.982653  0.993708
331  0.605874  0.653563  0.578146  0.546774  0.974497
332  0.952195  0.089713  0.325029  0.684682  0.597397
333  0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [47]:
newdf2[0][0] = 50

In [48]:
newdf

             0         1         2         3         4
0    50.000000  0.776558  0.769921  0.621858  0.038960
1     0.950114  0.889519  0.817604  0.582885  0.646131
2     0.979222  0.231910  0.205309  0.225336  0.717991
3     0.471485  0.774292  0.205895  0.623574  0.648689
4     0.013309  0.919097  0.670957  0.913508  0.307098
..         ...       ...       ...       ...       ...
329   0.440569  0.341099  0.164204  0.542524  0.973557
330   0.627435  0.237973  0.083605  0.982653  0.993708
331   0.605874  0.653563  0.578146  0.546774  0.974497
332   0.952195  0.089713  0.325029  0.684682  0.597397
333   0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [49]:
newdf2 = newdf.copy()

In [50]:
newdf2[0][0]= 100

C:\Users\HP\AppData\Local\Temp\ipykernel_8104\1281745750.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]= 100

In [51]:
newdf

             0         1         2         3         4
0    50.000000  0.776558  0.769921  0.621858  0.038960
1     0.950114  0.889519  0.817604  0.582885  0.646131
2     0.979222  0.231910  0.205309  0.225336  0.717991
3     0.471485  0.774292  0.205895  0.623574  0.648689
4     0.013309  0.919097  0.670957  0.913508  0.307098
..         ...       ...       ...       ...       ...
329   0.440569  0.341099  0.164204  0.542524  0.973557
330   0.627435  0.237973  0.083605  0.982653  0.993708
331   0.605874  0.653563  0.578146  0.546774  0.974497
332   0.952195  0.089713  0.325029  0.684682  0.597397
333   0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [52]:
newdf2

              0         1         2         3         4
0    100.000000  0.776558  0.769921  0.621858  0.038960
1      0.950114  0.889519  0.817604  0.582885  0.646131
2      0.979222  0.231910  0.205309  0.225336  0.717991
3      0.471485  0.774292  0.205895  0.623574  0.648689
4      0.013309  0.919097  0.670957  0.913508  0.307098
..          ...       ...       ...       ...       ...
329    0.440569  0.341099  0.164204  0.542524  0.973557
330    0.627435  0.237973  0.083605  0.982653  0.993708
331    0.605874  0.653563  0.578146  0.546774  0.974497
332    0.952195  0.089713  0.325029  0.684682  0.597397
333    0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [53]:
newdf.loc[0,0] = 99

In [54]:
newdf.head(2)

           0         1         2         3         4
0  99.000000  0.776558  0.769921  0.621858  0.038960
1   0.950114  0.889519  0.817604  0.582885  0.646131

In [55]:
newdf.columns = list("ABCDE")

In [56]:
newdf

             A         B         C         D         E
0    99.000000  0.776558  0.769921  0.621858  0.038960
1     0.950114  0.889519  0.817604  0.582885  0.646131
2     0.979222  0.231910  0.205309  0.225336  0.717991
3     0.471485  0.774292  0.205895  0.623574  0.648689
4     0.013309  0.919097  0.670957  0.913508  0.307098
..         ...       ...       ...       ...       ...
329   0.440569  0.341099  0.164204  0.542524  0.973557
330   0.627435  0.237973  0.083605  0.982653  0.993708
331   0.605874  0.653563  0.578146  0.546774  0.974497
332   0.952195  0.089713  0.325029  0.684682  0.597397
333   0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [57]:
newdf.loc[0,0] = 10

In [58]:
newdf

             A         B         C         D         E     0
0    99.000000  0.776558  0.769921  0.621858  0.038960  10.0
1     0.950114  0.889519  0.817604  0.582885  0.646131   NaN
2     0.979222  0.231910  0.205309  0.225336  0.717991   NaN
3     0.471485  0.774292  0.205895  0.623574  0.648689   NaN
4     0.013309  0.919097  0.670957  0.913508  0.307098   NaN
..         ...       ...       ...       ...       ...   ...
329   0.440569  0.341099  0.164204  0.542524  0.973557   NaN
330   0.627435  0.237973  0.083605  0.982653  0.993708   NaN
331   0.605874  0.653563  0.578146  0.546774  0.974497   NaN
332   0.952195  0.089713  0.325029  0.684682  0.597397   NaN
333   0.559361  0.662043  0.077973  0.987246  0.270846   NaN

[334 rows x 6 columns]

In [59]:
newdf.loc[0,'A'] = 10

In [60]:
newdf.head()

           A         B         C         D         E     0
0  10.000000  0.776558  0.769921  0.621858  0.038960  10.0
1   0.950114  0.889519  0.817604  0.582885  0.646131   NaN
2   0.979222  0.231910  0.205309  0.225336  0.717991   NaN
3   0.471485  0.774292  0.205895  0.623574  0.648689   NaN
4   0.013309  0.919097  0.670957  0.913508  0.307098   NaN

In [61]:
newdf.drop(0, axis = 1)

             A         B         C         D         E
0    10.000000  0.776558  0.769921  0.621858  0.038960
1     0.950114  0.889519  0.817604  0.582885  0.646131
2     0.979222  0.231910  0.205309  0.225336  0.717991
3     0.471485  0.774292  0.205895  0.623574  0.648689
4     0.013309  0.919097  0.670957  0.913508  0.307098
..         ...       ...       ...       ...       ...
329   0.440569  0.341099  0.164204  0.542524  0.973557
330   0.627435  0.237973  0.083605  0.982653  0.993708
331   0.605874  0.653563  0.578146  0.546774  0.974497
332   0.952195  0.089713  0.325029  0.684682  0.597397
333   0.559361  0.662043  0.077973  0.987246  0.270846

[334 rows x 5 columns]

In [62]:
newdf = newdf.drop(0, axis = 1)

In [63]:
newdf.head()

           A         B         C         D         E
0  10.000000  0.776558  0.769921  0.621858  0.038960
1   0.950114  0.889519  0.817604  0.582885  0.646131
2   0.979222  0.231910  0.205309  0.225336  0.717991
3   0.471485  0.774292  0.205895  0.623574  0.648689
4   0.013309  0.919097  0.670957  0.913508  0.307098

In [65]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.817604  0.582885
2  0.205309  0.225336

In [66]:
newdf.loc[:, ['C','D']]

            C         D
0    0.769921  0.621858
1    0.817604  0.582885
2    0.205309  0.225336
3    0.205895  0.623574
4    0.670957  0.913508
..        ...       ...
329  0.164204  0.542524
330  0.083605  0.982653
331  0.578146  0.546774
332  0.325029  0.684682
333  0.077973  0.987246

[334 rows x 2 columns]

In [67]:
newdf.loc[[1,2], :]

          A         B         C         D         E
1  0.950114  0.889519  0.817604  0.582885  0.646131
2  0.979222  0.231910  0.205309  0.225336  0.717991

In [69]:
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
4    0.013309  0.919097  0.670957  0.913508  0.307098
6    0.195840  0.759065  0.207983  0.283971  0.801792
10   0.263731  0.766781  0.168354  0.333143  0.093231
12   0.221231  0.121696  0.962831  0.612765  0.005264
13   0.079226  0.082616  0.841521  0.986516  0.340523
..        ...       ...       ...       ...       ...
320  0.240472  0.347203  0.409149  0.344983  0.834812
321  0.163834  0.041938  0.767913  0.057435  0.817906
322  0.063936  0.963744  0.053774  0.671168  0.653465
326  0.110436  0.650766  0.327397  0.390520  0.830910
327  0.179691  0.952231  0.120670  0.225822  0.253380

[99 rows x 5 columns]

In [70]:
 newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         E
4    0.013309  0.919097  0.670957  0.913508  0.307098
6    0.195840  0.759065  0.207983  0.283971  0.801792
10   0.263731  0.766781  0.168354  0.333143  0.093231
12   0.221231  0.121696  0.962831  0.612765  0.005264
13   0.079226  0.082616  0.841521  0.986516  0.340523
..        ...       ...       ...       ...       ...
319  0.172375  0.949771  0.416122  0.775223  0.465453
320  0.240472  0.347203  0.409149  0.344983  0.834812
321  0.163834  0.041938  0.767913  0.057435  0.817906
326  0.110436  0.650766  0.327397  0.390520  0.830910
327  0.179691  0.952231  0.120670  0.225822  0.253380

[90 rows x 5 columns]

In [71]:
newdf.head(2)

           A         B         C         D         E
0  10.000000  0.776558  0.769921  0.621858  0.038960
1   0.950114  0.889519  0.817604  0.582885  0.646131

In [73]:
newdf.iloc[0,4]

np.float64(0.03895991941676824)

In [74]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.776558  0.769921
1  0.889519  0.817604

In [75]:
newdf.head(3)

           A         B         C         D         E
0  10.000000  0.776558  0.769921  0.621858  0.038960
1   0.950114  0.889519  0.817604  0.582885  0.646131
2   0.979222  0.231910  0.205309  0.225336  0.717991

In [76]:
newdf.drop([0])

            A         B         C         D         E
1    0.950114  0.889519  0.817604  0.582885  0.646131
2    0.979222  0.231910  0.205309  0.225336  0.717991
3    0.471485  0.774292  0.205895  0.623574  0.648689
4    0.013309  0.919097  0.670957  0.913508  0.307098
5    0.819628  0.652225  0.829547  0.668876  0.248237
..        ...       ...       ...       ...       ...
329  0.440569  0.341099  0.164204  0.542524  0.973557
330  0.627435  0.237973  0.083605  0.982653  0.993708
331  0.605874  0.653563  0.578146  0.546774  0.974497
332  0.952195  0.089713  0.325029  0.684682  0.597397
333  0.559361  0.662043  0.077973  0.987246  0.270846

[333 rows x 5 columns]

In [77]:
newdf.drop(['E'], axis=1)

             A         B         C         D
0    10.000000  0.776558  0.769921  0.621858
1     0.950114  0.889519  0.817604  0.582885
2     0.979222  0.231910  0.205309  0.225336
3     0.471485  0.774292  0.205895  0.623574
4     0.013309  0.919097  0.670957  0.913508
..         ...       ...       ...       ...
329   0.440569  0.341099  0.164204  0.542524
330   0.627435  0.237973  0.083605  0.982653
331   0.605874  0.653563  0.578146  0.546774
332   0.952195  0.089713  0.325029  0.684682
333   0.559361  0.662043  0.077973  0.987246

[334 rows x 4 columns]

In [79]:
newdf.drop(['D','E'], axis=1)

             A         B         D
0    10.000000  0.776558  0.621858
1     0.950114  0.889519  0.582885
2     0.979222  0.231910  0.225336
3     0.471485  0.774292  0.623574
4     0.013309  0.919097  0.913508
..         ...       ...       ...
329   0.440569  0.341099  0.542524
330   0.627435  0.237973  0.982653
331   0.605874  0.653563  0.546774
332   0.952195  0.089713  0.684682
333   0.559361  0.662043  0.987246

[334 rows x 3 columns]

In [80]:
newdf.drop(['D','E'], axis=1, inplace=True)

In [81]:
newdf

             A         B         C
0    10.000000  0.776558  0.769921
1     0.950114  0.889519  0.817604
2     0.979222  0.231910  0.205309
3     0.471485  0.774292  0.205895
4     0.013309  0.919097  0.670957
..         ...       ...       ...
329   0.440569  0.341099  0.164204
330   0.627435  0.237973  0.083605
331   0.605874  0.653563  0.578146
332   0.952195  0.089713  0.325029
333   0.559361  0.662043  0.077973

[334 rows x 3 columns]

In [84]:
newdf.drop([1,5], axis=0, inplace=True)

In [85]:
newdf

             A         B         C
0    10.000000  0.776558  0.769921
2     0.979222  0.231910  0.205309
3     0.471485  0.774292  0.205895
4     0.013309  0.919097  0.670957
6     0.195840  0.759065  0.207983
..         ...       ...       ...
329   0.440569  0.341099  0.164204
330   0.627435  0.237973  0.083605
331   0.605874  0.653563  0.578146
332   0.952195  0.089713  0.325029
333   0.559361  0.662043  0.077973

[332 rows x 3 columns]

In [86]:
newdf.head(3)

           A         B         C
0  10.000000  0.776558  0.769921
2   0.979222  0.231910  0.205309
3   0.471485  0.774292  0.205895

In [87]:
newdf.reset_index()

     index          A         B         C
0        0  10.000000  0.776558  0.769921
1        2   0.979222  0.231910  0.205309
2        3   0.471485  0.774292  0.205895
3        4   0.013309  0.919097  0.670957
4        6   0.195840  0.759065  0.207983
..     ...        ...       ...       ...
327    329   0.440569  0.341099  0.164204
328    330   0.627435  0.237973  0.083605
329    331   0.605874  0.653563  0.578146
330    332   0.952195  0.089713  0.325029
331    333   0.559361  0.662043  0.077973

[332 rows x 4 columns]

In [89]:
newdf.reset_index(drop =True,inplace =True)

In [91]:
newdf.head(3)

           A         B         C
0  10.000000  0.776558  0.769921
1   0.979222  0.231910  0.205309
2   0.471485  0.774292  0.205895

In [93]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [94]:
newdf['B'] = None

In [95]:
newdf

             A     B         C
0    10.000000  None  0.769921
1     0.979222  None  0.205309
2     0.471485  None  0.205895
3     0.013309  None  0.670957
4     0.195840  None  0.207983
..         ...   ...       ...
327   0.440569  None  0.164204
328   0.627435  None  0.083605
329   0.605874  None  0.578146
330   0.952195  None  0.325029
331   0.559361  None  0.077973

[332 rows x 3 columns]

In [96]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [97]:
newdf.loc[:,['B']]=None

In [98]:
newdf

             A     B         C
0    10.000000  None  0.769921
1     0.979222  None  0.205309
2     0.471485  None  0.205895
3     0.013309  None  0.670957
4     0.195840  None  0.207983
..         ...   ...       ...
327   0.440569  None  0.164204
328   0.627435  None  0.083605
329   0.605874  None  0.578146
330   0.952195  None  0.325029
331   0.559361  None  0.077973

[332 rows x 3 columns]

In [99]:
newdf.loc[:,['B']]=5

In [101]:
newdf.head()

           A  B         C
0  10.000000  5  0.769921
1   0.979222  5  0.205309
2   0.471485  5  0.205895
3   0.013309  5  0.670957
4   0.195840  5  0.207983

In [102]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})

In [103]:
df.head()

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [104]:
df.dropna()

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [105]:
df.drop_duplicates()

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [106]:
df.drop_duplicates(subset=['brand'])

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5

In [107]:
df.drop_duplicates(subset=['brand'],keep ='last')

     brand style  rating
1  Yum Yum   cup     4.0
4  Indomie  pack     5.0

In [108]:
df.drop_duplicates(subset=['brand'],keep =False)

Empty DataFrame
Columns: [brand, style, rating]
Index: []

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   brand   5 non-null      object
 1   style   5 non-null      object
 2   rating  5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 252.0+ bytes

In [111]:
df['brand'].value_counts(dropna = False)

brand
Indomie    3
Yum Yum    2
Name: count, dtype: int64

In [112]:
df.notnull()

   brand  style  rating
0   True   True    True
1   True   True    True
2   True   True    True
3   True   True    True
4   True   True    True

In [113]:
df.isnull()

   brand  style  rating
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False

In [114]:
 data = pd.read_excel('data.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.